using AtelieDaTransformacao.Desktop.Themes;

namespace AtelieDaTransformacao.Desktop.Forms;
partial class CategoryDialog
{
    private System.ComponentModel.IContainer? components=null;private Guna.UI2.WinForms.Guna2BorderlessForm _borderlessForm=null!;private Guna.UI2.WinForms.Guna2DragControl _dragControl=null!;private Guna.UI2.WinForms.Guna2Panel _headerPanel=null!;private Guna.UI2.WinForms.Guna2Panel _bodyPanel=null!;private Label _titleLabel=null!;private Label _nameCaption=null!;private Label _descriptionCaption=null!;private Guna.UI2.WinForms.Guna2TextBox _nameTextBox=null!;private Guna.UI2.WinForms.Guna2TextBox _descriptionTextBox=null!;private Guna.UI2.WinForms.Guna2Button _cancelButton=null!;private Guna.UI2.WinForms.Guna2Button _saveButton=null!;
    protected override void Dispose(bool disposing){if(disposing)components?.Dispose();base.Dispose(disposing);}private void InitializeComponent(){components=new System.ComponentModel.Container();_borderlessForm=new Guna.UI2.WinForms.Guna2BorderlessForm(components);_dragControl=new Guna.UI2.WinForms.Guna2DragControl(components);_headerPanel=new Guna.UI2.WinForms.Guna2Panel();_bodyPanel=new Guna.UI2.WinForms.Guna2Panel();_titleLabel=new Label();_nameCaption=new Label();_descriptionCaption=new Label();_nameTextBox=new Guna.UI2.WinForms.Guna2TextBox();_descriptionTextBox=new Guna.UI2.WinForms.Guna2TextBox();_cancelButton=new Guna.UI2.WinForms.Guna2Button();_saveButton=new Guna.UI2.WinForms.Guna2Button();SuspendLayout();_borderlessForm.ContainerControl=this;_borderlessForm.BorderRadius=14;_borderlessForm.ShadowColor=Color.Black;_dragControl.TargetControl=_headerPanel;FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.CenterParent;ClientSize=new Size(560,390);BackColor=Color.White;Text="Categoria";_headerPanel.Dock=DockStyle.Top;_headerPanel.Height=76;_headerPanel.FillColor=Color.White;_headerPanel.Controls.Add(_titleLabel);_titleLabel.AutoSize=true;_titleLabel.Text="Categoria";_titleLabel.Font=new Font("Segoe UI",17F,FontStyle.Bold);_titleLabel.ForeColor=LibraryTheme.Text;_titleLabel.Location=new Point(24,20);_bodyPanel.Dock=DockStyle.Fill;_bodyPanel.FillColor=Color.White;_bodyPanel.Controls.Add(_saveButton);_bodyPanel.Controls.Add(_cancelButton);_bodyPanel.Controls.Add(_descriptionTextBox);_bodyPanel.Controls.Add(_nameTextBox);_bodyPanel.Controls.Add(_descriptionCaption);_bodyPanel.Controls.Add(_nameCaption);ConfigureCaption(_nameCaption,"Nome",24,18);ConfigureText(_nameTextBox,24,40,500,42,"Nome da categoria");ConfigureCaption(_descriptionCaption,"Descrição",24,92);_descriptionTextBox.Location=new Point(24,114);_descriptionTextBox.Size=new Size(500,90);_descriptionTextBox.Multiline=true;_descriptionTextBox.BorderRadius=9;_descriptionTextBox.BorderColor=LibraryTheme.Border;_descriptionTextBox.FocusedState.BorderColor=LibraryTheme.Accent;_descriptionTextBox.PlaceholderText="Descrição da categoria";ConfigureButton(_cancelButton,"Cancelar",274,110,false);ConfigureButton(_saveButton,"Salvar",398,110,true);_cancelButton.DialogResult=DialogResult.Cancel;AcceptButton=_saveButton;CancelButton=_cancelButton;Controls.Add(_bodyPanel);Controls.Add(_headerPanel);ResumeLayout(false);}
    private static void ConfigureCaption(Label l,string t,int x,int y){l.AutoSize=true;l.Text=t;l.Font=new Font("Segoe UI Semibold",8.5F);l.ForeColor=LibraryTheme.Text;l.Location=new Point(x,y);}private static void ConfigureText(Guna.UI2.WinForms.Guna2TextBox t,int x,int y,int w,int h,string ph){t.Location=new Point(x,y);t.Size=new Size(w,h);t.BorderRadius=9;t.BorderColor=LibraryTheme.Border;t.FocusedState.BorderColor=LibraryTheme.Accent;t.PlaceholderText=ph;t.Font=new Font("Segoe UI",9.5F);}private static void ConfigureButton(Guna.UI2.WinForms.Guna2Button b,string text,int x,int y,bool primary){b.Location=new Point(x,238);b.Size=new Size(y,42);b.Text=text;b.BorderRadius=9;b.FillColor=primary?LibraryTheme.Accent:Color.FromArgb(241,243,248);b.ForeColor=primary?Color.White:LibraryTheme.Text;b.Font=new Font("Segoe UI Semibold",9F);b.HoverState.FillColor=primary?LibraryTheme.AccentDark:Color.FromArgb(225,229,238);}
}
