using AtelieDaTransformacao.Desktop.Themes;

namespace AtelieDaTransformacao.Desktop.Forms;
partial class ProductDialog
{
    private System.ComponentModel.IContainer? components=null;private Guna.UI2.WinForms.Guna2BorderlessForm _borderlessForm=null!;private Guna.UI2.WinForms.Guna2DragControl _dragControl=null!;private Guna.UI2.WinForms.Guna2Panel _headerPanel=null!;private Label _titleLabel=null!;private Guna.UI2.WinForms.Guna2Panel _bodyPanel=null!;private Guna.UI2.WinForms.Guna2TextBox _titleTextBox=null!;private Guna.UI2.WinForms.Guna2TextBox _descriptionTextBox=null!;private Guna.UI2.WinForms.Guna2NumericUpDown _priceNumeric=null!;private Guna.UI2.WinForms.Guna2NumericUpDown _stockNumeric=null!;private Guna.UI2.WinForms.Guna2ComboBox _categoryComboBox=null!;private Guna.UI2.WinForms.Guna2CheckBox _featuredCheckBox=null!;private Guna.UI2.WinForms.Guna2Button _cancelButton=null!;private Guna.UI2.WinForms.Guna2Button _saveButton=null!;private Label _nameCaption=null!;private Label _descriptionCaption=null!;private Label _priceCaption=null!;private Label _stockCaption=null!;private Label _categoryCaption=null!;
    protected override void Dispose(bool disposing){if(disposing)components?.Dispose();base.Dispose(disposing);}
    private void InitializeComponent(){components=new System.ComponentModel.Container();_borderlessForm=new Guna.UI2.WinForms.Guna2BorderlessForm(components);_dragControl=new Guna.UI2.WinForms.Guna2DragControl(components);_headerPanel=new Guna.UI2.WinForms.Guna2Panel();_titleLabel=new Label();_bodyPanel=new Guna.UI2.WinForms.Guna2Panel();_titleTextBox=new Guna.UI2.WinForms.Guna2TextBox();_descriptionTextBox=new Guna.UI2.WinForms.Guna2TextBox();_priceNumeric=new Guna.UI2.WinForms.Guna2NumericUpDown();_stockNumeric=new Guna.UI2.WinForms.Guna2NumericUpDown();_categoryComboBox=new Guna.UI2.WinForms.Guna2ComboBox();_featuredCheckBox=new Guna.UI2.WinForms.Guna2CheckBox();_cancelButton=new Guna.UI2.WinForms.Guna2Button();_saveButton=new Guna.UI2.WinForms.Guna2Button();_nameCaption=new Label();_descriptionCaption=new Label();_priceCaption=new Label();_stockCaption=new Label();_categoryCaption=new Label();SuspendLayout();
        _borderlessForm.ContainerControl=this;_borderlessForm.BorderRadius=14;_borderlessForm.ShadowColor=Color.Black;_dragControl.TargetControl=_headerPanel;FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.CenterParent;ClientSize=new Size(620,650);BackColor=LibraryTheme.Background;Text="Produto";
        _headerPanel.Dock=DockStyle.Top;_headerPanel.Height=78;_headerPanel.FillColor=Color.White;_headerPanel.Controls.Add(_titleLabel);_titleLabel.AutoSize=true;_titleLabel.Text="Produto";_titleLabel.Font=new Font("Segoe UI",17F,FontStyle.Bold);_titleLabel.ForeColor=LibraryTheme.Text;_titleLabel.Location=new Point(24,22);
        _bodyPanel.Dock=DockStyle.Fill;_bodyPanel.FillColor=Color.White;_bodyPanel.Padding=new Padding(24);_bodyPanel.Controls.Add(_saveButton);_bodyPanel.Controls.Add(_cancelButton);_bodyPanel.Controls.Add(_featuredCheckBox);_bodyPanel.Controls.Add(_categoryComboBox);_bodyPanel.Controls.Add(_stockNumeric);_bodyPanel.Controls.Add(_priceNumeric);_bodyPanel.Controls.Add(_descriptionTextBox);_bodyPanel.Controls.Add(_titleTextBox);_bodyPanel.Controls.Add(_categoryCaption);_bodyPanel.Controls.Add(_stockCaption);_bodyPanel.Controls.Add(_priceCaption);_bodyPanel.Controls.Add(_descriptionCaption);_bodyPanel.Controls.Add(_nameCaption);
        ConfigureCaption(_nameCaption,"Nome",24,18);ConfigureText(_titleTextBox,24,40,540,42,"Nome do produto");ConfigureCaption(_descriptionCaption,"Descrição",24,88);_descriptionTextBox.Location=new Point(24,110);_descriptionTextBox.Size=new Size(540,78);_descriptionTextBox.Multiline=true;_descriptionTextBox.BorderRadius=9;_descriptionTextBox.BorderColor=LibraryTheme.Border;_descriptionTextBox.FocusedState.BorderColor=LibraryTheme.Accent;_descriptionTextBox.PlaceholderText="Descrição do produto";ConfigureCaption(_priceCaption,"Preço",24,204);_priceNumeric.Location=new Point(24,226);_priceNumeric.Size=new Size(255,42);_priceNumeric.DecimalPlaces=2;_priceNumeric.Maximum=1000000;_priceNumeric.Minimum=.01M;_priceNumeric.Increment=.50M;_priceNumeric.BorderRadius=9;_priceNumeric.BorderColor=LibraryTheme.Border;ConfigureCaption(_stockCaption,"Estoque",306,204);_stockNumeric.Location=new Point(306,226);_stockNumeric.Size=new Size(258,42);_stockNumeric.Maximum=100000;_stockNumeric.BorderRadius=9;_stockNumeric.BorderColor=LibraryTheme.Border;ConfigureCaption(_categoryCaption,"Categoria",24,274);_categoryComboBox.Location=new Point(24,296);_categoryComboBox.Size=new Size(540,42);_categoryComboBox.DropDownStyle=ComboBoxStyle.DropDownList;_categoryComboBox.BorderRadius=9;_categoryComboBox.BorderColor=LibraryTheme.Border;_categoryComboBox.Font=new Font("Segoe UI",9.5F);_featuredCheckBox.Location=new Point(24,352);_featuredCheckBox.Text="Produto em destaque";_featuredCheckBox.CheckedState.FillColor=LibraryTheme.Accent;_featuredCheckBox.Font=new Font("Segoe UI",9F);_featuredCheckBox.AutoSize=true;
        ConfigureButton(_cancelButton,"Cancelar",314,118,false);ConfigureButton(_saveButton,"Salvar",446,118,true);_cancelButton.DialogResult=DialogResult.Cancel;AcceptButton=_saveButton;CancelButton=_cancelButton;
        Controls.Add(_bodyPanel);Controls.Add(_headerPanel);ResumeLayout(false);
    }
    private static void ConfigureCaption(Label l,string t,int x,int y){l.AutoSize=true;l.Text=t;l.Font=new Font("Segoe UI Semibold",8.5F);l.ForeColor=LibraryTheme.Text;l.Location=new Point(x,y);}private static void ConfigureText(Guna.UI2.WinForms.Guna2TextBox t,int x,int y,int w,int h,string ph){t.Location=new Point(x,y);t.Size=new Size(w,h);t.BorderRadius=9;t.BorderColor=LibraryTheme.Border;t.FocusedState.BorderColor=LibraryTheme.Accent;t.PlaceholderText=ph;t.Font=new Font("Segoe UI",9.5F);}
    private static void ConfigureButton(Guna.UI2.WinForms.Guna2Button b,string text,int x,int w,bool primary){b.Location=new Point(x,420);b.Size=new Size(w,42);b.Text=text;b.BorderRadius=9;b.FillColor=primary?LibraryTheme.Accent:Color.FromArgb(241,243,248);b.ForeColor=primary?Color.White:LibraryTheme.Text;b.Font=new Font("Segoe UI Semibold",9F);b.HoverState.FillColor=primary?LibraryTheme.AccentDark:Color.FromArgb(225,229,238);}
}
