using AtelieDaTransformacao.Desktop.Themes;

namespace AtelieDaTransformacao.Desktop.Forms;
partial class SimpleUserDialog
{
    private System.ComponentModel.IContainer? components=null;private Guna.UI2.WinForms.Guna2BorderlessForm _borderlessForm=null!;private Guna.UI2.WinForms.Guna2DragControl _dragControl=null!;private Guna.UI2.WinForms.Guna2Panel _headerPanel=null!;private Guna.UI2.WinForms.Guna2Panel _bodyPanel=null!;private Label _titleLabel=null!;private Label _emailCaption=null!;private Label _passwordCaption=null!;private Guna.UI2.WinForms.Guna2TextBox _emailTextBox=null!;private Guna.UI2.WinForms.Guna2TextBox _passwordTextBox=null!;private Guna.UI2.WinForms.Guna2Button _cancelButton=null!;private Guna.UI2.WinForms.Guna2Button _createButton=null!;
    protected override void Dispose(bool disposing){if(disposing)components?.Dispose();base.Dispose(disposing);}private void InitializeComponent(){components=new System.ComponentModel.Container();_borderlessForm=new Guna.UI2.WinForms.Guna2BorderlessForm(components);_dragControl=new Guna.UI2.WinForms.Guna2DragControl(components);_headerPanel=new Guna.UI2.WinForms.Guna2Panel();_bodyPanel=new Guna.UI2.WinForms.Guna2Panel();_titleLabel=new Label();_emailCaption=new Label();_passwordCaption=new Label();_emailTextBox=new Guna.UI2.WinForms.Guna2TextBox();_passwordTextBox=new Guna.UI2.WinForms.Guna2TextBox();_cancelButton=new Guna.UI2.WinForms.Guna2Button();_createButton=new Guna.UI2.WinForms.Guna2Button();SuspendLayout();_borderlessForm.ContainerControl=this;_borderlessForm.BorderRadius=14;_borderlessForm.ShadowColor=Color.Black;_dragControl.TargetControl=_headerPanel;FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.CenterParent;ClientSize=new Size(520,360);BackColor=Color.White;Text="Novo usuário";_headerPanel.Dock=DockStyle.Top;_headerPanel.Height=76;_headerPanel.FillColor=Color.White;_headerPanel.Controls.Add(_titleLabel);_titleLabel.AutoSize=true;_titleLabel.Text="Novo usuário";_titleLabel.Font=new Font("Segoe UI",17F,FontStyle.Bold);_titleLabel.ForeColor=LibraryTheme.Text;_titleLabel.Location=new Point(24,20);_bodyPanel.Dock=DockStyle.Fill;_bodyPanel.FillColor=Color.White;_bodyPanel.Controls.Add(_createButton);_bodyPanel.Controls.Add(_cancelButton);_bodyPanel.Controls.Add(_passwordTextBox);_bodyPanel.Controls.Add(_emailTextBox);_bodyPanel.Controls.Add(_passwordCaption);_bodyPanel.Controls.Add(_emailCaption);ConfigureCaption(_emailCaption,"E-mail",24,18);ConfigureText(_emailTextBox,24,40,"seu@email.com",false);ConfigureCaption(_passwordCaption,"Senha",24,92);ConfigureText(_passwordTextBox,24,114,"Mínimo de 6 caracteres",true);ConfigureButton(_cancelButton,"Cancelar",272,110,false);ConfigureButton(_createButton,"Criar",396,110,true);_cancelButton.DialogResult=DialogResult.Cancel;AcceptButton=_createButton;CancelButton=_cancelButton;Controls.Add(_bodyPanel);Controls.Add(_headerPanel);ResumeLayout(false);}
    private static void ConfigureCaption(Label l,string t,int x,int y){l.AutoSize=true;l.Text=t;l.Font=new Font("Segoe UI Semibold",8.5F);l.ForeColor=LibraryTheme.Text;l.Location=new Point(x,y);}private static void ConfigureText(Guna.UI2.WinForms.Guna2TextBox t,int x,int y,string ph,bool password){t.Location=new Point(x,y);t.Size=new Size(472,42);t.BorderRadius=9;t.BorderColor=LibraryTheme.Border;t.FocusedState.BorderColor=LibraryTheme.Accent;t.PlaceholderText=ph;t.Font=new Font("Segoe UI",9.5F);if(password)t.PasswordChar='●';}private static void ConfigureButton(Guna.UI2.WinForms.Guna2Button b,string text,int x,int y,bool primary){b.Location=new Point(x,180);b.Size=new Size(y,42);b.Text=text;b.BorderRadius=9;b.FillColor=primary?LibraryTheme.Accent:Color.FromArgb(241,243,248);b.ForeColor=primary?Color.White:LibraryTheme.Text;b.Font=new Font("Segoe UI Semibold",9F);b.HoverState.FillColor=primary?LibraryTheme.AccentDark:Color.FromArgb(225,229,238);}
}
